#!/usr/bin/env python3
"""
scripts/ci/protect_accepted_md.py
=================================
CI guard: run from the repo root after extractors and BEFORE `git add`.

Accepted (git HEAD) Markdown / JSON / HTML under the protected roots must never
be rewritten or deleted by a bot run:

  * data/extracted/md/
  * corpus/

1. Tracked files modified or deleted in the working tree vs HEAD are restored
   with `git checkout HEAD -- <paths>`.
2. Untracked files whose lowercased path equals the lowercased path of a tracked
   file (case-variant duplicates that collide on Windows / macOS) are deleted.

Brand-new files are left alone so genuine additions are still committed.

Not protected (legitimately regenerated by every run): files placed directly in
corpus/ (inventory / audit registries) and any file whose basename starts with
"_" (state / index files such as _gated_links.json).

Env:   ALLOW_MD_REWRITE=1  report only, change nothing.
Flags: --dry-run           report only, change nothing.
Exit:  0 unless git itself fails.
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from collections import Counter
from pathlib import PurePosixPath

PROTECTED_ROOTS = ("data/extracted/md/", "corpus/")
PROTECTED_EXTS = (".md", ".json", ".html", ".htm")
LIST_LIMIT = 20


class GitError(RuntimeError):
    pass


def git(args: list[str], input_bytes: bytes | None = None) -> bytes:
    cmd = ["git", "-c", "core.quotepath=off", "--literal-pathspecs", *args]
    proc = subprocess.run(cmd, input=input_bytes, capture_output=True)
    if proc.returncode != 0:
        raise GitError(
            f"{' '.join(cmd)} failed ({proc.returncode}): "
            f"{proc.stderr.decode('utf-8', 'replace').strip()}"
        )
    return proc.stdout


def split_z(raw: bytes) -> list[str]:
    return [p.decode("utf-8", "surrogateescape") for p in raw.split(b"\0") if p]


def is_protected(path: str) -> bool:
    if not path.startswith(PROTECTED_ROOTS):
        return False
    if not path.lower().endswith(PROTECTED_EXTS):
        return False
    pp = PurePosixPath(path)
    if pp.name.startswith("_"):
        return False
    if path.startswith("corpus/") and len(pp.parts) == 2:
        return False
    return True


def group_of(path: str) -> str:
    parts = PurePosixPath(path).parts
    if path.startswith("data/extracted/md/") and len(parts) > 3:
        return f"md/{parts[3]}"
    return f"corpus/{parts[1]}" if len(parts) > 2 else parts[0]


def summarize(title: str, paths: list[str]) -> None:
    print(f"{title}: {len(paths)}")
    for grp, n in sorted(Counter(group_of(p) for p in paths).items()):
        print(f"  {grp}: {n}")
    for p in paths[:LIST_LIMIT]:
        print(f"    {p}")
    if len(paths) > LIST_LIMIT:
        print(f"    ... and {len(paths) - LIST_LIMIT} more")


def find_damaged() -> list[str]:
    roots = list(PROTECTED_ROOTS)
    changed = split_z(git(["diff", "--name-only", "--no-renames", "-z", "--diff-filter=MD", "HEAD", "--", *roots]))
    deleted = split_z(git(["ls-files", "-z", "--deleted", "--", *roots]))
    return sorted({p for p in changed + deleted if is_protected(p)})


def find_case_collisions() -> list[str]:
    roots = list(PROTECTED_ROOTS)
    tracked = set(split_z(git(["ls-tree", "-r", "--name-only", "-z", "HEAD", "--", *roots])))
    tracked_lower = {p.lower() for p in tracked}
    untracked = split_z(git(["ls-files", "-z", "--others", "--", *roots]))
    staged_new = split_z(git(["diff", "--cached", "--name-only", "--no-renames", "-z",
                              "--diff-filter=A", "HEAD", "--", *roots]))
    return sorted(
        p for p in set(untracked) | set(staged_new)
        if p not in tracked and is_protected(p) and p.lower() in tracked_lower
    )


def staged_paths(paths: list[str]) -> set[str]:
    return set(split_z(git(["diff", "--cached", "--name-only", "-z", "--diff-filter=A",
                            "HEAD", "--", *paths]))) if paths else set()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--dry-run", action="store_true", help="report only; change nothing")
    args = ap.parse_args(argv)
    report_only = args.dry_run or os.environ.get("ALLOW_MD_REWRITE") == "1"

    try:
        root = git(["rev-parse", "--show-toplevel"]).decode("utf-8").strip()
        os.chdir(root)
        damaged = find_damaged()
        collisions = find_case_collisions()

        if not damaged and not collisions:
            print("protect_accepted_md: no accepted files modified, deleted or case-duplicated.")
            return 0

        mode = "REPORT ONLY" if report_only else "ENFORCING"
        print(f"protect_accepted_md [{mode}]")

        if damaged:
            summarize("Accepted files modified/deleted vs HEAD" +
                      ("" if report_only else " (reverting)"), damaged)
            if not report_only:
                payload = b"\0".join(p.encode("utf-8", "surrogateescape") for p in damaged) + b"\0"
                git(["checkout", "HEAD", "--pathspec-from-file=-", "--pathspec-file-nul"], payload)
            verb = "would revert" if report_only else "reverted"
            print(f"::warning::protect_accepted_md {verb} {len(damaged)} accepted file(s) "
                  f"(first: {damaged[0]})")

        if collisions:
            summarize("Case-variant duplicates of tracked files" +
                      ("" if report_only else " (deleting)"), collisions)
            if not report_only:
                staged = staged_paths(collisions)
                if staged:
                    git(["rm", "--cached", "-q", "--", *sorted(staged)])
                for p in collisions:
                    try:
                        os.remove(p)
                    except FileNotFoundError:
                        pass
            verb = "would remove" if report_only else "removed"
            print(f"::warning::protect_accepted_md {verb} {len(collisions)} case-variant "
                  f"duplicate file(s) (first: {collisions[0]})")
    except GitError as exc:
        print(f"::error::protect_accepted_md git failure: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
