"""Targeted cell-level fixer for Carriers S&P weekly markdown (data/extracted/md/carriers).

The Carriers MDs are machine-generated by one template (scripts/extract/publishers/
run_carriers.py geometry parser) and are audited "good except" a few defect classes.
This tool repairs ONLY the defective cells; every other byte of the MD is preserved.

Every new value is read from the PDF text layer (or, for sentiment, the colour of the
arrow glyph in the PDF text layer). Nothing is computed. Classes:

* dotzero   - float rendering of a printed integer ("1296.0" -> "1296"); the PDF token
              (e.g. "1,296" / "1296") is the evidence.
* trailing0 - printed 3-decimal token that lost its trailing zero ("3.59" -> "3.590").
* thousands - Tanker TCE cells printed with a dot as thousands separator ("38.806" is
              $38,806). Fixed only when the printed Week Ch. cell proves it: the printed
              change equals (this - previous) of the printed digits (-5551 = 38806 - 44357).
* sentiment - arrow glyph colour in the PDF: green (00b050) = UP, red (ff0000/ee0000) =
              DOWN, black = unresolved (never guessed; cell is left unchanged and reported).
* blank_na  - BDA/BSPA price cell blank in the MD but printed "N/A" in the PDF.

Source markdown is never modified: fixed copies go to .reparse_staging/carriers/.

Usage:
    python -m scripts.md_cleanup.carriers_fix [--detect-only] [--limit N] [--years 2025,2026]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
MAIN_CHECKOUT = Path(r"C:\Users\Dell\Github\Shipping")
MD_ROOT_REL = Path("data/extracted/md/carriers")
STAGING_REL = Path(".reparse_staging/carriers")
PDF_ROOT_REL = Path("corpus/01-brokers/carriers")

ARROW = "\ua71b"
SECTION_LABELS = {"TANKERS", "BULKERS", "CONTAINERS"}
CRLF = chr(13) + chr(10)
LF = chr(10)
GREEN = {0x00B050}
RED = {0xFF0000, 0xEE0000}


# ---------------------------------------------------------------- markdown model
def parse_md_tables(lines: list[str]) -> list[dict]:
    """Return tables: {title, header, rows:[(line_idx, cells)]} in file order."""
    tables, title, i = [], None, 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("## "):
            title = ln[3:].strip()
        if ln.startswith("|") and i + 1 < len(lines) and re.match(r"^\|(\s*---\s*\|)+\s*$", lines[i + 1]):
            hdr = split_row(ln)
            rows, j = [], i + 2
            while j < len(lines) and lines[j].startswith("|"):
                rows.append((j, split_row(lines[j])))
                j += 1
            tables.append({"title": title, "header": hdr, "hdr_line": i, "rows": rows})
            i = j
            continue
        i += 1
    return tables


def split_row(line: str) -> list[str]:
    body = line.strip()
    body = body[1:-1] if body.endswith("|") else body[1:]
    return [c.strip() for c in body.split(" | ")] if " | " in body else [c.strip() for c in body.split("|")]


def join_row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


# ---------------------------------------------------------------- PDF model
def page_spans(page) -> list[dict]:
    out = []
    for b in page.get_text("dict")["blocks"]:
        for l in b.get("lines", []):
            for s in l["spans"]:
                if s["text"].strip():
                    x0, y0, x1, y1 = s["bbox"]
                    out.append({"x0": x0, "x1": x1, "yc": (y0 + y1) / 2, "text": s["text"],
                                "color": s["color"]})
    return out


RELEVANT_KEYS = ("Reported Sold", "Demolition Market", "Newbuilding Market", "BSPA", "TCE",
                 "Time Charter", "DIRTY")


def relevant_pages(doc) -> list:
    """Pages carrying report tables (the Greek-equities page is excluded by the same rule
    the MDs were built with: it has none of these table headings)."""
    return [p for p in doc if any(k in p.get_text() for k in RELEVANT_KEYS)]


def arrow_colour_name(rgb: int) -> str:
    if rgb in GREEN:
        return "green"
    if rgb in RED:
        return "red"
    return "other"


def page2_arrows(page) -> list[dict]:
    """Every arrow glyph on the page with its table key (section, row label), colour."""
    spans = page_spans(page)
    heads = {}
    for s in spans:
        t = s["text"].strip()
        if t.startswith("Sale and Purchase Index"):
            heads["idx"] = s["yc"]
        if t.startswith("Newbuilding Index"):
            heads["nbi"] = s["yc"]
        if t.startswith("Dry BC Baltic Indices"):
            heads["dry"] = s["yc"]
    idx_y = heads.get("idx", 1e9)
    has_bspa = any(s["text"].strip().startswith("BSPA as reported") for s in spans)
    if not has_bspa:
        idx_y = -1e9
    res = []
    for a in spans:
        if ARROW not in a["text"]:
            continue
        # arrow glyph x position: right end of the span (arrow is the last char)
        ax = a["x1"]
        rec = {"y": a["yc"], "x": ax, "rgb": a["color"], "colour": arrow_colour_name(a["color"]),
               "span_text": a["text"].strip()}
        if a["yc"] < idx_y:
            half = "BSPA" if ax < page.rect.width / 2 else "BDA"
            if half == "BSPA":
                cands = [s for s in spans if s["x1"] < 150 and abs(s["yc"] - a["yc"]) < 6
                         and re.match(r"^[A-Z][A-Za-z ]+$", s["text"].strip())
                         and s["text"].strip().upper() not in SECTION_LABELS]
            else:
                cands = [s for s in spans if page.rect.width / 2 - 40 < s["x0"] < 330 and abs(s["yc"] - a["yc"]) < 6
                         and re.match(r"^(TANKERS|CONTAINERS|BULKERS)$", s["text"].strip())]
            rec["section"] = half
            cands.sort(key=lambda s: abs(s["yc"] - a["yc"]))
            rec["label"] = cands[0]["text"].strip() if cands else None
        else:
            cands = [s for s in spans if re.match(r"^[A-Z]{4}$", s["text"].strip())
                     and abs(s["yc"] - a["yc"]) < 6 and s["x1"] < ax - 3]
            cands.sort(key=lambda s: s["x1"])
            rec["section"] = "INDEX"
            rec["label"] = cands[-1]["text"].strip() if cands else None
        res.append(rec)
    return res


# ---------------------------------------------------------------- PDF evidence
def pdf_tokens(doc) -> dict[str, str]:
    """normalised token (commas removed) -> printed token, all table pages (page-wide; not used as row evidence)."""
    toks: dict[str, str] = {}
    for pg in relevant_pages(doc):
        for w in pg.get_text("words"):
            t = w[4].replace(ARROW, "").strip()
            if t:
                toks.setdefault(t.replace(",", ""), t)
    return toks


HEADINGS = ("Second-hand Market", "Demolition Market", "Newbuilding Market", "BSPA as reported",
            "Sale and Purchase Index", "Recycling Index", "Newbuilding Index", "Dry BC Baltic Indices")
SPLIT_X = 270.0


def page_words(doc) -> list[dict]:
    """Per relevant page: word boxes plus the y of every table heading."""
    out = []
    for pg in relevant_pages(doc):
        words = []
        for w in pg.get_text("words"):
            tx = w[4].replace(ARROW, "").strip()
            if tx:
                words.append({"x0": w[0], "x1": w[2], "yc": (w[1] + w[3]) / 2, "text": tx})
        heads = []
        for s in page_spans(pg):
            for h in HEADINGS:
                if s["text"].strip().startswith(h):
                    heads.append((s["yc"], h))
        out.append({"words": words, "heads": sorted(heads)})
    return out


ROW_HEADS = {"Second-hand": "Second-hand Market", "Demolition": "Demolition Market",
             "Newbuilding Market": "Newbuilding Market"}


def bound_tokens(pw: list[dict], title: str | None, cells: list[str]) -> dict[str, str] | None:
    """Printed tokens (comma-free key -> printed text) located in the PDF band of THIS row
    (row-oriented tables) or under THIS column header (column-oriented tables).
    None when the table kind cannot be bound."""
    t = title or ""
    toks: dict[str, str] = {}
    col_mode, head, tol, split, label = False, None, 4.0, False, None
    if t.startswith(tuple(ROW_HEADS)):
        head = next(v for k, v in ROW_HEADS.items() if t.startswith(k))
        tol, label = 7.0, cells[0].split()[0].upper() if cells[0].split() else None
    elif t.startswith("BSPA"):
        split, label = True, cells[1].split()[0].upper()
    elif t.startswith("BDA"):
        split, label = True, cells[0].split()[0].upper()
    elif t.startswith("Market & Baltic Indices"):
        if cells[0] == "Baltic Dry Indices":
            col_mode, label = True, cells[1].upper()
        else:
            split, label = True, cells[1].upper()
    elif t.startswith("Dry BC Baltic Time Charter Weighted") or t.startswith("Dry BC Time Charter Period"):
        col_mode, label = True, cells[0].split()[0].upper()
    elif t.startswith("Tanker Rates"):
        w = cells[0].split()
        col_mode, label = True, (w[1] if w[0] == "Baltic" and len(w) > 1 else w[0]).upper()
    else:
        return None
    if not label:
        return None
    for page in pw:
        words, heads = page["words"], page["heads"]
        lo, hi = -1e9, 1e9
        if head:
            ys = [y for y, h in heads if h == head]
            if not ys:
                continue
            lo = ys[0]
            nxt = [y for y, h in heads if y > lo and h != head]
            hi = min(nxt) if nxt else 1e9
        for lw in words:
            if lw["text"].upper() != label or not (lo <= lw["yc"] <= hi):
                continue
            if col_mode:
                for w in words:
                    cx = (w["x0"] + w["x1"]) / 2
                    if lw["x0"] - 25 <= cx <= lw["x1"] + 45 and lw["yc"] < w["yc"] <= lw["yc"] + 140:
                        toks.setdefault(w["text"].replace(",", ""), w["text"])
            else:
                left = lw["x0"] < SPLIT_X
                for w in words:
                    if abs(w["yc"] - lw["yc"]) > tol:
                        continue
                    if split and ((w["x0"] < SPLIT_X) != left):
                        continue
                    toks.setdefault(w["text"].replace(",", ""), w["text"])
    return toks


def page2_na(page) -> list[dict]:
    """Printed N/A cells in the BSPA (left) / BDA (right) boxes with their row label."""
    spans = page_spans(page)
    idx_y = min((s["yc"] for s in spans if s["text"].strip().startswith("Sale and Purchase Index")),
                default=1e9)
    out = []
    if not any(s["text"].strip().startswith("BSPA as reported") for s in spans):
        return out
    for s in spans:
        if s["text"].strip() != "N/A" or s["yc"] >= idx_y:
            continue
        if s["x0"] > page.rect.width / 2:
            lab = [c for c in spans if page.rect.width / 2 - 40 < c["x0"] < 330 and abs(c["yc"] - s["yc"]) < 6
                   and re.match(r"^(TANKERS|CONTAINERS|BULKERS)$", c["text"].strip())]
            sec = "BDA"
        else:
            lab = [c for c in spans if c["x1"] < 150 and abs(c["yc"] - s["yc"]) < 6
                   and re.match(r"^[A-Z][A-Z ]+$", c["text"].strip())
                   and c["text"].strip() not in SECTION_LABELS]
            sec = "BSPA"
        lab.sort(key=lambda c: abs(c["yc"] - s["yc"]))
        if lab:
            out.append({"section": sec, "label": lab[0]["text"].strip()})
    return out


# ---------------------------------------------------------------- detection / fixing
TANKER_ROWS = ("VLCC TCE", "SUEZ TCE", "AFRA TCE", "MR ATLANTIC TC routes")


def _title_kind(title: str | None) -> str | None:
    t = title or ""
    for k, kind in (("BSPA", "BSPA"), ("BDA", "BDA"), ("Market & Baltic Indices", "INDEX"),
                    ("Tanker Rates", "TANKER"), ("Demolition", "DEMO"), ("Second-hand", "SALES")):
        if t.startswith(k):
            return kind
    return None


def fix_document(md_text: str, doc) -> tuple[str, list[dict], list[dict]]:
    """Return (fixed_text, changes, unresolved). Only defective cells are rewritten."""
    lines = md_text.split("\n")
    pw = page_words(doc)
    arrows = [a for pg in relevant_pages(doc) for a in page2_arrows(pg)]
    nas = [n for pg in relevant_pages(doc) for n in page2_na(pg)]
    tables = parse_md_tables(lines)
    changes, unresolved = [], []

    def put(ln, ci, cells, new, cls, evidence, tbl, key, col):
        old = cells[ci]
        if new == old:
            return
        cells[ci] = new
        changes.append({"line": ln + 1, "table": tbl["title"], "row": key, "column": col,
                        "old": old, "new": new, "class": cls, "pdf_evidence": evidence})

    for tbl in tables:
        kind = _title_kind(tbl["title"])
        hdr = tbl["header"]
        for ln, cells in tbl["rows"]:
            if len(cells) != len(hdr):
                continue
            orig = list(cells)
            key = " | ".join(cells[:2])
            toks = bound_tokens(pw, tbl["title"], cells)
            if toks is None:
                toks = {}
                unbound = True
            else:
                unbound = False
            if kind == "TANKER" and cells[0] in TANKER_ROWS and len(cells) == 4:
                t, c, p = cells[1], cells[2], cells[3]
                if re.fullmatch(r"\d+\.\d{3}", t) and re.fullmatch(r"\d+\.\d{3}", p):
                    chg = re.sub(r"\.0$", "", c)
                    if re.fullmatch(r"-?\d+", chg) and t in toks and p in toks \
                            and chg in toks:
                        if int(t.replace(".", "")) - int(p.replace(".", "")) == int(chg):
                            ev = (f"PDF printed {t} / {toks[chg]} / {p}; printed change "
                                  f"{chg} == {t.replace('.', '')} - {p.replace('.', '')}")
                            put(ln, 1, cells, t.replace(".", ""), "thousands", ev, tbl, key, hdr[1])
                            put(ln, 3, cells, p.replace(".", ""), "thousands", ev, tbl, key, hdr[3])
                        else:
                            unresolved.append({"line": ln + 1, "class": "thousands", "row": key,
                                               "reason": "printed change does not match printed digits"})
                    else:
                        unresolved.append({"line": ln + 1, "class": "thousands", "row": key,
                                           "reason": "printed token not found in PDF text layer"})
            for ci, v in enumerate(list(cells)):
                col = hdr[ci]
                if re.fullmatch(r"-?\d+\.0", v):
                    ip = v[:-2]
                    if v in toks:
                        continue
                    if ip in toks:
                        put(ln, ci, cells, ip, "dotzero", f"PDF printed {toks[ip]}",
                            tbl, key, col)
                    else:
                        unresolved.append({"line": ln + 1, "class": "dotzero", "row": key,
                                           "column": col, "value": v,
                                           "reason": "table not row-bindable" if unbound
                                           else "no printed token in this row/column band"})
                elif kind in ("BSPA", "INDEX") and re.fullmatch(r"\d+\.\d{1,2}", v) and v not in toks:
                    hits = [pt for n, pt in toks.items() if re.fullmatch(r"\d+\.\d{3}", n)
                            and n.startswith(v) and float(n) == float(v)]
                    if len(hits) == 1:
                        put(ln, ci, cells, hits[0], "trailing0", f"PDF printed {hits[0]}", tbl, key, col)
            if kind in ("BSPA", "BDA"):
                lab = (cells[1] if kind == "BSPA" else cells[0]).upper()
                pcol = "Price ($M)" if "Price ($M)" in hdr else "Price ($/LDT)"
                if pcol in hdr:
                    pi = hdr.index(pcol)
                    if cells[pi] == "" and any(n["section"] == kind and n["label"].upper() == lab
                                               for n in nas):
                        put(ln, pi, cells, "N/A", "blank_na", f"PDF printed N/A on row {lab}",
                            tbl, key, pcol)
            if "Sentiment" in hdr and kind in ("BSPA", "BDA", "INDEX"):
                si = hdr.index("Sentiment")
                lab = {"BSPA": cells[1], "BDA": cells[0], "INDEX": cells[1]}[kind].upper()
                hit = [a for a in arrows if a["section"] == kind and (a["label"] or "").upper() == lab]
                if len(hit) == 1:
                    a = hit[0]
                    new = {"green": "UP", "red": "DOWN"}.get(a["colour"])
                    if new:
                        put(ln, si, cells, new, "sentiment",
                            f"PDF arrow glyph colour #{a['rgb']:06x} ({a['colour']}) on row {lab}",
                            tbl, key, "Sentiment")
                    else:
                        unresolved.append({"line": ln + 1, "class": "sentiment", "row": key,
                                           "reason": f"arrow colour #{a['rgb']:06x} is neither green nor red"})
                elif cells[si] == "UP":
                    unresolved.append({"line": ln + 1, "class": "sentiment", "row": key,
                                       "reason": f"MD says UP but PDF has {len(hit)} arrows for this row"})
            if cells != orig:
                lines[ln] = join_row(cells)
    return "\n".join(lines), changes, unresolved


# ---------------------------------------------------------------- structure detection (report only)
SALE_TYPES = {"BC", "TANKER", "CV", "LPG", "GC", "RORO", "CONT", "MPP", "LNG"}


def structure_defects(md_text: str, doc) -> dict:
    """Report-only defects that need the engine, not a cell fix."""
    tables = parse_md_tables(md_text.split("\n"))
    out = {"width_mismatch_rows": 0, "demolition_shifted_rows": 0, "missing_vessels": []}
    names = set()
    for tbl in tables:
        hdr = tbl["header"]
        kind = _title_kind(tbl["title"])
        for ln, cells in tbl["rows"]:
            if len(cells) != len(hdr):
                out["width_mismatch_rows"] += 1
            if kind == "DEMO" and len(cells) > 1 and re.fullmatch(r"[\d,]+", cells[1]):
                out["demolition_shifted_rows"] += 1
            if kind == "SALES":
                names.add(re.sub(r"\s+", " ", cells[0]).upper())
    txt = [l.strip() for l in doc[0].get_text().split("\n")]
    for i in range(len(txt) - 2):
        if txt[i + 1] in SALE_TYPES and re.fullmatch(r"\d{1,3}(,\d{3})*", txt[i + 2]) and txt[i] \
                and txt[i] not in SALE_TYPES and re.sub(r"\s+", " ", txt[i]).upper() not in names:
            out["missing_vessels"].append(txt[i])
    return out


# ---------------------------------------------------------------- driver
def resolve_pdf(md_text: str) -> Path | None:
    m = re.search(r"^source_file:\s*\"?([^\"\n]+)\"?", md_text, flags=re.M)
    if not m:
        return None
    rel = Path(m.group(1).strip())
    for root in (REPO_ROOT, MAIN_CHECKOUT):
        if (root / rel).exists():
            return root / rel
    return None


def run(years: list[str] | None, limit: int | None, detect_only: bool, out_root: Path) -> dict:
    import pymupdf
    summary = {"files": 0, "files_changed": 0, "cells_changed": 0, "no_pdf": [], "by_year_class": {},
               "unresolved": Counter(), "structure": {}, "per_file_changes": {}}
    byyc: dict = defaultdict(Counter)
    paths = sorted((REPO_ROOT / MD_ROOT_REL).glob("*/*.md"))
    if years:
        paths = [p for p in paths if p.parent.name in years]
    if limit:
        paths = paths[:limit]
    for p in paths:
        raw = p.read_bytes().decode("utf-8")
        eol = CRLF if CRLF in raw else LF
        txt = raw.replace(CRLF, LF)
        if txt.replace(LF, eol) != raw:
            summary["no_pdf"].append(p.name + " (mixed line endings, skipped)")
            continue
        pdf = resolve_pdf(txt)
        yr = p.parent.name
        summary["files"] += 1
        if pdf is None:
            summary["no_pdf"].append(p.name)
            continue
        doc = pymupdf.open(pdf)
        new, ch, un = fix_document(txt, doc)
        sd = structure_defects(txt, doc)
        summary["structure"][p.name] = {k: v for k, v in sd.items() if v}
        for c in ch:
            byyc[yr][c["class"]] += 1
        for u in un:
            summary["unresolved"][f"{yr}:{u['class']}"] += 1
        if ch:
            summary["files_changed"] += 1
            summary["cells_changed"] += len(ch)
            summary["per_file_changes"][p.name] = len(ch)
            if not detect_only:
                d = out_root / yr
                d.mkdir(parents=True, exist_ok=True)
                (d / p.name).write_text(new.replace(LF, eol), encoding="utf-8", newline="")
                (d / (p.stem + ".changelog.json")).write_text(
                    json.dumps({"md": str(MD_ROOT_REL / yr / p.name), "pdf": pdf.name,
                                "source_sha256": hashlib.sha256(raw.encode("utf-8")).hexdigest(),
                                "changes": ch, "unresolved": un}, indent=1, ensure_ascii=False),
                    encoding="utf-8")
    summary["by_year_class"] = {y: dict(c) for y, c in byyc.items()}
    summary["unresolved"] = dict(summary["unresolved"])
    return summary


def apply_staged(staging: Path, md_root: Path, do_apply: bool) -> dict:
    """Copy staged MDs over the real MDs, only for files that have a changelog and whose
    source is byte-identical to what the fixer read. Dry-run unless do_apply."""
    res = {"applied": [], "refused": [], "dry_run": not do_apply}
    for log in sorted(staging.glob("*/*.changelog.json")):
        meta = json.loads(log.read_text(encoding="utf-8"))
        staged = log.with_name(log.name[: -len(".changelog.json")] + ".md")
        target = REPO_ROOT / meta["md"]
        if not meta.get("changes") or not staged.exists() or not target.exists():
            res["refused"].append({"file": log.name, "reason": "no changes / missing staged or target"})
            continue
        if hashlib.sha256(target.read_bytes()).hexdigest() != meta.get("source_sha256"):
            res["refused"].append({"file": log.name, "reason": "target changed since staging"})
            continue
        if do_apply:
            target.write_bytes(staged.read_bytes())
        res["applied"].append(str(target.relative_to(REPO_ROOT)))
    return res


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--detect-only", action="store_true")
    ap.add_argument("--limit", type=int)
    ap.add_argument("--years")
    ap.add_argument("--apply", action="store_true",
                    help="promote staged files that have changelogs into data/extracted/md/carriers")
    ap.add_argument("--dry-run", action="store_true", help="with promotion, list only (default)")
    ap.add_argument("--promote", action="store_true", help="list/apply staged files, do not re-run the fixer")
    a = ap.parse_args()
    if a.apply or a.promote:
        r = apply_staged(REPO_ROOT / STAGING_REL, REPO_ROOT / MD_ROOT_REL, a.apply and not a.dry_run)
        print(json.dumps({"dry_run": r["dry_run"], "applied": len(r["applied"]), "refused": r["refused"]},
                         indent=1))
        return
    s = run(a.years.split(",") if a.years else None, a.limit, a.detect_only, REPO_ROOT / STAGING_REL)
    out = REPO_ROOT / STAGING_REL
    out.mkdir(parents=True, exist_ok=True)
    (out / "_summary.json").write_text(json.dumps(s, indent=1, ensure_ascii=False), encoding="utf-8")
    print(json.dumps({k: v for k, v in s.items() if k not in ("structure", "per_file_changes")},
                     indent=1, ensure_ascii=False))


if __name__ == "__main__":
    main()
